### PR TITLE
Lokesh Manchi FP2

### PR DESCRIPTION
**Pull request by lokeshmanchi**

### CODE REVIEW

**Comment by marksherman** [comment]
Dare I ask you for an embedded image? A diagram? anything? please? for me?

**Comment by marksherman** [comment]
@lokeshmanchi  You have until class time on thursday.

**Comment by marksherman** [comment]
👌 

http://i.imgur.com/JId1jfM.jpg

**Comment by lokeshmanchi** [comment]
Haaahahahaaa

**Pull request closed without merging**
