### PR TITLE
FP2 Resubmission

### PR DESCRIPTION
**Pull request by eampadu**
Submitting FP2.

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Ebenezer, 

You named this pull request FP1. Just mentioning.

I see that you have 3 images in your repository. That's good.

But, you need to figure out how to incorporate images into the readme.MD file. 

Look at someone else's submission to see what I mean -- e.g. https://github.com/skhoulani/FP2.

I am marking this incomplete until you figure this out.

When you have it fixed, reply by adding a comment here. DO NOT issue a new pull request.

Thanks.

**Comment by marksherman** [comment]
@eampadu reminder this still needs updating as Fred said above.

**Comment by eampadu** [comment]
Dear Professor Sherman:

My other course works have held me back a little bit; but I will fix the issues soon.

Thank you for your time and consideration.

Sincerely,

Ebenezer Ampadu

**Comment by marksherman** [comment]
Images are good. Please format code using the backticks (lower-case ~) so it looks like code.

**Comment by eampadu** [comment]
@fgmart : Updated source code.
@marksherman

**Comment by marksherman** [comment]
Close enough! 

You can encase whole blocks of code in triple-backticks to make code blocks, like this:

```
(define (mc-eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((quoted? exp) (text-of-quotation exp))
        ((assignment? exp) (eval-assignment exp env))
        ((definition? exp) (eval-definition exp env))
        ((if? exp) (eval-if exp env))
```

**Pull request closed without merging**
