### PR TITLE
2nd Project Exploration

### PR DESCRIPTION
**Pull request by BrendanBousquet**
Played around with image encryption using some graphics tools in conjunction with the standard image library.  Worked pretty well.  Similar to the project in Computing 4 with SFML.  Was interesting to find a different method of doing essentially the same thing.

### CODE REVIEW

**Comment by marksherman** [comment]
Extremely cool. Great write up. What is that .rkt file? It surely isn't racket source.

**Comment by BrendanBousquet** [comment]
It may be a little weird because there's a define statement with the actual image pasted into the source. The tutorial I used did it that way. I thought it might mess it up which is why I attached the image as well. I can submit the racket file again without that line if that's what you would like. 

-Brendan Bousquet

**Comment by BrendanBousquet** [comment]
Ok so I've altered encrypt.rkt with some instruction on how it can be run if that is necessary for grading.    The racket source should be opened in DrRacket and then beach.png should be copied and pasted directly into the line that is commented with instructions to do so.  It wasn't opening on GitHub because it makes the source file very large compared to when the image is not there.  That or the ability to paste the image is a feature of the graphics tools I downloaded but I am almost certain it can be done in DrRacket by default.  Hope this clears everything up.  Let me know if there is anything else to fix.

**Comment by fgmart-zz** [comment]
image and dsheap color utils. good work brendan.

**Pull request closed without merging**
